version: '3'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meh
    expose:
      - "5432"
    ports:
      - "2345:5432"
